# calling both same function from animal and bird module.

# approach 1:
# import c_animal
# import d_bird
#
# c_animal.fly()      #animal can't fly...
# c_animal.color()    #animal is black...
#
# d_bird.fly()        #bird can fly...
# d_bird.color()      #bird is green...

#approach 2:
from c_animal import *
fly()        #animal can't fly...
color()     ##animal is black...

from d_bird import *
fly()       #bird can fly...
color()     #bird is green...